# Solving Sudoku

The primary description of this coursework is available on the CM20252 Moodle page. This is the Jupyter notebook you must complete and submit to receive marks. 

** You must follow all instructions given in this notebook. **

Restart the kernel and run all cells before submitting the notebook. This will guarantee that we will be able to run your code for testing.

Remember to save your work regularly. 

## Getting Started

You already know that you will be writing a Sudoku solver. You need to implement your solver in Python in this notebook. You can use any of the appropriate problem-solving techniques discussed in the lectures. You are encouraged to modify the basic algorithms. Be creative. 

You will be given Sudoku puzzles that either have a single solution or no solution. You will need to identify the solution, if there is one.

Below is a sample puzzle along with its solution. 

<img src="resources/images/Sudoku_unsolved.png" style="width: 200px;"/>
<img src="resources/images/Sudoku_solved.png" style="width: 200px;"/>


## Sample Sudokus

You can test your code on a set of 100 sample Sudoku puzzles. This set is similar to the test set that will be used to assess your work. 

The following code will load 100 Sudoku puzzles and their solutions into two `100x9x9` numpy arrays. Empty cells are designated by zeros. 

In [1]:
import numpy as np

# Load sudokus
sudokus = np.load("resources/data/sudokus.npy")
print("Shape of sudokus array:", sudokus.shape, "; Type of array values:", sudokus.dtype)

# Load solutions
solutions = np.load("resources/data/solutions.npy")
print("Shape of solutions array:", solutions.shape, "; Type of array values:", solutions.dtype, "\n")

# Print the first sudoku...
print("Sudoku #1:")
print(sudokus[0], "\n")

# ...and its solution
print("Solution of Sudoku #1:")
print(solutions[0])


'''WHEN TESTED ON OWN COMPUTER - ALL TESTS PASSED'''
# Load sudokus
#sudokus = np.load(r"C:\Users\Chakib\Downloads\aic1_sudoku (1)\resources\data\sudokus.npy")
#print("Shape of sudokus array:", sudokus.shape, "; Type of array values:", sudokus.dtype)

#solvable_samples = np.load(r"C:\Users\Chakib\Downloads\sudoku-sample-1000 (1).npy")

#unsolvable_samples = np.load(r"C:\Users\Chakib\Downloads\sudoku-sample-15-unsolvable.npy")

#Load solutions
#solutions = np.load(r"C:\Users\Chakib\Downloads\aic1_sudoku (1)\resources\data\solutions.npy")
#print("Shape of solutions array:", solutions.shape, "; Type of array values:", solutions.dtype, "\n")

#Print the first sudoku...
#print("Sudoku #1:")
#print(sudokus[0], "\n")

#...and its solution
#print("Solution of Sudoku #1:")
#print(solutions[0])

FileNotFoundError: [Errno 2] No such file or directory: 'resources/data/sudokus.npy'

## Your code ##

Define a function called `sudoku_solver()` that takes **one** Sudoku puzzle (a $9 \times 9$ numpy array) as input and returns the solved Sudoku as a $9 \times 9$ numpy array. Note that the test set may contain invalid Sudokus, that is, Sudokus with no solution. In such a case, your function should return a $9 \times 9$ numpy array whose values are all equal to `-1`.  

You may use more than one cell to write your code (but this is not necessary).

In [7]:
import numpy as np
import time

'''This function produces a one dimensional array of size 9 for all
   elements in the grid that have positions defined by (x,y)  '''
def grid(A, x ,y):
        
    # both i and j are used to determine where (x,y) are located
    i = x % 3
    j = y % 3
    
    # row_diff and col_diff are starting positions in the contrsuction of the grid
    row_diff = x - i
    m = row_diff + 1
    n = row_diff + 2
    
    col_diff = y - j
    o = col_diff + 1
    p = col_diff + 2

    # array produced which contains all values for the grid
    grid_array = [A[m,col_diff], A[n,col_diff], A[row_diff,o], A[m,o], A[n, o],
          A[row_diff, p], A[m, p], A[n, p], A[row_diff,col_diff]]
    
    return grid_array

'''This function goes through all possible entries that can be inserted into 
   the grid. For an entry to be considered, it must not be held in a position in which
   a column,row or 3x3 grid hold the same value'''
def possible_entries(sudoku, column, row):
    
    entry_values  = []
    
    # gets the whole row, column, and box for the sudoku position
    columns = sudoku[column, :]
    rows = sudoku[:, row]
    grid_array = grid(sudoku, column, row)
    
    #loops through all possible values to see which values can be placed in grid
    for value in range (1,10):
        if not value in rows:
            if not value in columns:
                if not value in grid_array:
                    entry_values.append(value)
            
    
    return entry_values
            
'''This function solves the sudoku using constraint propagation

   Input: sudoku, 9x9 numpy array of integers
            Empty cells are designated by 0.

   Output: 9x9 numpy array of integers. It contains the solution, if there is one.
           If there is no solution, all array entries should be -1.'''            
def sudoku_solver(sudoku):
   
    
    A = np.copy(sudoku)
    
    not_solvable = np.full((9, 9), -1, dtype=int)
        
    #iterating through whole sudoku grid making sure no zeros remain
    boolean = True
    while(boolean == True):
        boolean = False
        for k in range(0,9):
            for l in range(0,9):
                if A[k,l] == 0:
                    boolean = True
                    # possible_entries are obtained
                    value_options = possible_entries(A,k,l)
                    if len(value_options) == 1:
                        #if there is only one possible_entry, the cell is updated
                        A[k,l] = value_options[0]
                    if len(value_options) == 0:
                        #if there does not exist a possible_entry, the sudoku grid has no solution
                        return not_solvable
                        
    
    return A

'''Testing sudoku_solver() on different set of sudoku puzzles'''
# Load sudokus
sudokus = np.load("resources/data/sudokus.npy")
solvable_samples = np.load("resources/data/sudoku-sample-1000 (1).npy")
unsolvable_samples =  np.load("resources/data/sudoku-sample-15-unsolvable.npy")

# Load solutions
solutions = np.load("resources/data/solutions.npy")


# solving sudokus
start = time.time()

'''solvable and unsolvable solutions must be tested seperately - ALL TESTS PASSED'''
for i in range(100):
    hundred_sudokus = sudoku_solver(sudokus[i])
    print(hundred_sudokus, "\n") 
    
#for i in range (1000):
    #solvable = sudoku_solver(solvable_samples[i])
    #print(solvable, "\n")
    
#for i in range (15):
   #unsolvable = sudoku_solver(unsolvable_samples[i])
    #print(unsolvable, "\n")
    

end = time.time()
print("Sudoku puzzles solved in",end - start,"seconds")

http://localhost:8888/notebooks/aic1_sudoku.ipynb#



[[8 6 4 3 7 1 2 5 9]
 [3 2 5 8 4 9 7 6 1]
 [9 7 1 2 6 5 8 4 3]
 [4 3 6 1 9 2 5 8 7]
 [1 9 8 6 5 7 4 3 2]
 [2 5 7 4 8 3 9 1 6]
 [6 8 9 7 3 4 1 2 5]
 [7 1 3 5 2 8 6 9 4]
 [5 4 2 9 1 6 3 7 8]] 

[[3 4 6 1 7 9 2 5 8]
 [1 8 7 5 2 3 9 6 4]
 [5 2 9 6 4 8 3 7 1]
 [9 6 5 8 3 2 4 1 7]
 [4 7 2 9 1 6 8 3 5]
 [8 1 3 7 5 4 6 2 9]
 [7 9 8 2 6 1 5 4 3]
 [6 3 1 4 8 5 7 9 2]
 [2 5 4 3 9 7 1 8 6]] 

[[6 9 5 1 2 7 3 8 4]
 [1 3 8 4 5 9 6 7 2]
 [7 2 4 8 3 6 9 1 5]
 [8 5 1 2 6 4 7 3 9]
 [2 7 3 9 8 1 5 4 6]
 [9 4 6 5 7 3 8 2 1]
 [3 1 7 6 9 2 4 5 8]
 [4 8 9 7 1 5 2 6 3]
 [5 6 2 3 4 8 1 9 7]] 

[[4 9 7 2 5 8 3 1 6]
 [1 8 6 4 3 9 7 2 5]
 [2 5 3 7 1 6 4 9 8]
 [6 2 9 3 8 1 5 4 7]
 [3 7 5 9 6 4 1 8 2]
 [8 4 1 5 7 2 6 3 9]
 [9 6 2 1 4 5 8 7 3]
 [7 1 8 6 2 3 9 5 4]
 [5 3 4 8 9 7 2 6 1]] 

[[4 6 5 9 1 2 3 7 8]
 [1 8 9 4 7 3 5 6 2]
 [3 2 7 5 6 8 1 4 9]
 [7 3 8 6 4 5 2 9 1]
 [9 5 4 8 2 1 6 3 7]
 [2 1 6 3 9 7 8 5 4]
 [5 7 3 2 8 4 9 1 6]
 [6 4 2 1 5 9 7 8 3]
 [8 9 1 7 3 6 4 2 5]] 

[[1 9 4 6 8 5 2 3 7]
 [3 8 2 9 7 4 5 1 6

[[1 9 2 5 6 7 4 3 8]
 [8 7 3 4 2 9 1 5 6]
 [5 6 4 1 8 3 2 7 9]
 [3 8 7 9 4 2 6 1 5]
 [2 5 1 8 7 6 3 9 4]
 [9 4 6 3 5 1 8 2 7]
 [7 3 9 6 1 4 5 8 2]
 [6 1 8 2 9 5 7 4 3]
 [4 2 5 7 3 8 9 6 1]] 

[[9 6 3 7 5 2 4 8 1]
 [4 5 1 3 6 8 9 7 2]
 [7 2 8 4 9 1 3 5 6]
 [8 9 2 1 7 6 5 3 4]
 [1 7 4 5 3 9 2 6 8]
 [6 3 5 8 2 4 1 9 7]
 [5 1 9 6 4 7 8 2 3]
 [3 8 7 2 1 5 6 4 9]
 [2 4 6 9 8 3 7 1 5]] 

[[8 5 1 3 4 7 6 9 2]
 [4 9 6 5 8 2 1 7 3]
 [7 2 3 1 6 9 4 5 8]
 [3 8 2 6 7 5 9 1 4]
 [5 1 4 2 9 8 3 6 7]
 [6 7 9 4 1 3 2 8 5]
 [1 4 8 7 2 6 5 3 9]
 [9 6 5 8 3 4 7 2 1]
 [2 3 7 9 5 1 8 4 6]] 

[[1 5 8 4 7 9 6 3 2]
 [9 6 3 2 8 1 4 7 5]
 [4 7 2 5 6 3 9 1 8]
 [2 1 5 8 3 6 7 9 4]
 [6 8 4 7 9 2 1 5 3]
 [3 9 7 1 5 4 8 2 6]
 [5 2 1 9 4 8 3 6 7]
 [8 3 9 6 2 7 5 4 1]
 [7 4 6 3 1 5 2 8 9]] 

[[1 8 7 2 3 5 4 9 6]
 [2 6 4 8 9 1 7 3 5]
 [3 9 5 6 7 4 1 8 2]
 [4 2 6 3 8 9 5 7 1]
 [7 1 9 5 4 2 8 6 3]
 [8 5 3 7 1 6 2 4 9]
 [9 3 8 1 5 7 6 2 4]
 [5 4 2 9 6 8 3 1 7]
 [6 7 1 4 2 3 9 5 8]] 

[[1 2 7 3 9 8 5 4 6]
 [6 5 4 1 7 2 3 9 8

[[6 4 7 2 3 8 5 1 9]
 [9 1 5 4 7 6 2 3 8]
 [3 2 8 5 1 9 4 6 7]
 [7 9 1 6 5 2 8 4 3]
 [5 6 3 7 8 4 9 2 1]
 [4 8 2 3 9 1 7 5 6]
 [8 3 9 1 2 5 6 7 4]
 [2 7 6 8 4 3 1 9 5]
 [1 5 4 9 6 7 3 8 2]] 

Sudoku puzzles solved in 0.9197831153869629 seconds


## Testing your code

You can test your code on the sudoku puzzles that we have provided. For example, the following code cell should return `True` if your `sudoku_solver()` function can correctly solve the first sudoku. This will work only if all of your code is above the test cell. Otherwise, the test cell does not have access to the `sudoku_solver()` function.

In [8]:
np.array_equal(sudoku_solver(sudokus[0]), solutions[0])
    


NameError: name 'solutions' is not defined

## How we will test your code

We will test your code using the hidden tests in the following cell. Specifically, the hidden tests will test your `sudoku_solver()` function on a different set of 100 sudoku puzzles of similar difficulty. **Make sure all of your code is above our test cell. ** Otherwise, the test cell will not have access to the sudoku_solver() function and you will receive zero marks.

In [3]:
# This is the TEST CELL. Do not delete or change. All of your code must be written above this cell. 
